CREATE TABLE books (
id SERIAL PRIMARY KEY,
author VARCHAR(255) NOT NULL,
title VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE posts (
id SERIAL PRIMARY KEY,
book_id INTEGER REFERENCES books(id),
category VARCHAR(255) NOT NULL,
content TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE posts ADD COLUMN agree INTEGER;
ALTER TABLE posts ADD COLUMN disagree INTEGER;
ALTER TABLE posts ADD COLUMN incorrect INTEGER;
ALTER TABLE posts ADD COLUMN spam INTEGER;
